"""add position to chapter

Revision ID: 202171266e7a
Revises: b7705741d5a6
Create Date: 2025-08-11 11:17:27.879534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202171266e7a'
down_revision = 'b7705741d5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
