"""adding notes to chapter

Revision ID: 7f0d2b4cf9f9
Revises: 0b5373afb684
Create Date: 2025-08-20 12:07:32.829955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0d2b4cf9f9'
down_revision = '0b5373afb684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
