"""add summary to Tome

Revision ID: b7705741d5a6
Revises: 
Create Date: 2025-07-22 13:57:29.587223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7705741d5a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tomes', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
